### ISSUE TITLE
Service specific resources

### ISSUE THREAD

**Issue by FranOis** [aiven/terraform-aiven-services#3]
This is more up for a general design discussion. While I like the flexibility of having a very generic service resource that allows this provider to support any new service that aiven could add to their offering without having to write more code. The downside to this is that you have to manage all service type in the same file or do some kind of logic switch between type plus managing a giant map of possible configuration that depends on the service type. This causes issues with clarity of use and makes it hard to understand exactly what's possible to do and what is not possible to do on a service basis.

My proposal is as follows.
1. Keep the very generic service resource for backward compatibility and for future work by aiven and to support any service that are not yet implemented in this provider.
2. Implement a service type specific resource for each offering of aiven.

For example:
You would still have the service resource as it exists now, but we would also have one for Kafke, Postgres, ElasticSearch etc.

**Comment by jelmersnoeck** [comment]
Thanks for this (and all the PRs!).

I will have a deeper look into this and get back to you about it, but in general I like the idea.

**Comment by rikonen** [comment]
A new implementation that was merged today keeps the generic service resource for all services but there are `<service_type>_user_config` maps that define any attributes that are specific to certain service, which is (mostly) automatically generated and doesn't need manual maintenance when new service type specific attributes are added (apart from re-running a script to regenerate some files). This would seem like decent enough compromise. The service resource, which now supports all service types and attributes, is less than 600 lines of code.
